In [ ]:
import pandas as pd

import yfinance as yf
aapl=yf.Ticker("AAPL")
price_df=aapl.history(period="1mo")

print("shape:", price_df.shape)
print("Columns:",price_df.columns.tolist())
price_df.head()

:

In [7]:
expiries = aapl.options

print("Number of expiries:", len(expiries))
print(expiries)

Number of expiries: 22
('2026-04-27', '2026-04-29', '2026-05-01', '2026-05-04', '2026-05-08', '2026-05-15', '2026-05-22', '2026-05-29', '2026-06-18', '2026-07-17', '2026-08-21', '2026-09-18', '2026-10-16', '2026-11-20', '2026-12-18', '2027-01-15', '2027-03-19', '2027-06-17', '2027-12-17', '2028-01-21', '2028-03-17', '2028-12-15')

In [8]:
first_expiry = expiries[15]
chain = aapl.option_chain(first_expiry)

calls_df = chain.calls
puts_df = chain.puts

print("Selected expiry:", first_expiry)
print("Calls shape:", calls_df.shape)
print("Puts shape:", puts_df.shape)

calls_df.head()

Selected expiry: 2027-01-15
Calls shape: (72, 14)
Puts shape: (64, 14)

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,AAPL270115C00005000,2026-04-22 19:51:49+00:00,5.0,267.90,264.15,267.65,0.0,0.0,5,123,3.156252,True,REGULAR,USD
1,AAPL270115C00010000,2026-04-22 19:51:49+00:00,10.0,262.91,259.30,262.65,0.0,0.0,10,42,2.383793,True,REGULAR,USD
2,AAPL270115C00015000,2026-04-22 19:51:49+00:00,15.0,257.87,254.25,257.60,0.0,0.0,5,15,2.004888,True,REGULAR,USD
3,AAPL270115C00020000,2026-03-02 14:31:52+00:00,20.0,241.50,0.00,0.00,0.0,0.0,3,0,0.000010,True,REGULAR,USD
4,AAPL270115C00025000,2025-05-23 17:36:45+00:00,25.0,172.10,174.80,178.65,0.0,0.0,3,5,0.000010,True,REGULAR,USD

In [9]:
print(calls_df.columns.tolist())

['contractSymbol', 'lastTradeDate', 'strike', 'lastPrice', 'bid', 'ask', 'change', 'percentChange', 'volume', 'openInterest', 'impliedVolatility', 'inTheMoney', 'contractSize', 'currency']

In [10]:
print(calls_df.columns.tolist())
print(calls_df.dtypes)
calls_df[["contractSymbol", "strike", "bid", "ask", "volume", "openInterest", "impliedVolatility"]].head()

['contractSymbol', 'lastTradeDate', 'strike', 'lastPrice', 'bid', 'ask', 'change', 'percentChange', 'volume', 'openInterest', 'impliedVolatility', 'inTheMoney', 'contractSize', 'currency']
contractSymbol                    object
lastTradeDate        datetime64[ns, UTC]
strike                           float64
lastPrice                        float64
bid                              float64
ask                              float64
change                           float64
percentChange                    float64
volume                             int64
openInterest                       int64
impliedVolatility                float64
inTheMoney                          bool
contractSize                      object
currency                          object
dtype: object

,contractSymbol,strike,bid,ask,volume,openInterest,impliedVolatility
0,AAPL270115C00005000,5.0,264.15,267.65,5,123,3.156252
1,AAPL270115C00010000,10.0,259.30,262.65,10,42,2.383793
2,AAPL270115C00015000,15.0,254.25,257.60,5,15,2.004888
3,AAPL270115C00020000,20.0,0.00,0.00,3,0,0.000010
4,AAPL270115C00025000,25.0,174.80,178.65,3,5,0.000010

In [11]:
str(calls_df)

'         contractSymbol             lastTradeDate  strike  lastPrice     bid  \\\n0   AAPL270115C00005000 2026-04-22 19:51:49+00:00     5.0     267.90  264.15   \n1   AAPL270115C00010000 2026-04-22 19:51:49+00:00    10.0     262.91  259.30   \n2   AAPL270115C00015000 2026-04-22 19:51:49+00:00    15.0     257.87  254.25   \n3   AAPL270115C00020000 2026-03-02 14:31:52+00:00    20.0     241.50    0.00   \n4   AAPL270115C00025000 2025-05-23 17:36:45+00:00    25.0     172.10  174.80   \n..                  ...                       ...     ...        ...     ...   \n67  AAPL270115C00510000 2026-04-24 13:30:09+00:00   510.0       0.15    0.13   \n68  AAPL270115C00520000 2026-04-23 16:20:45+00:00   520.0       0.14    0.10   \n69  AAPL270115C00530000 2026-04-24 18:11:21+00:00   530.0       0.10    0.08   \n70  AAPL270115C00540000 2026-04-20 18:15:04+00:00   540.0       0.12    0.08   \n71  AAPL270115C00550000 2026-04-24 16:43:17+00:00   550.0       0.09    0.06   \n\n       ask  change  percentChange  volume  openInterest  impliedVolatility  \\\n0   267.65    0.00       0.000000       5           123           3.156252   \n1   262.65    0.00       0.000000      10            42           2.383793   \n2   257.60    0.00       0.000000       5            15           2.004888   \n3     0.00    0.00       0.000000       3             0           0.000010   \n4   178.65    0.00       0.000000       3             5           0.000010   \n..     ...     ...            ...     ...           ...                ...   \n67    0.17   -0.05     -24.999998      30            90           0.293464   \n68    0.17    0.00       0.000000      10           331           0.301277   \n69    0.12   -0.02     -16.666664     220          4640           0.297370   \n70    0.11    0.00       0.000000     157           718           0.301765   \n71    0.09    0.01      12.500008      20          5933           0.302253   \n\n    inTheMoney contractSize currency  \n0         True      REGULAR      USD  \n1         True      REGULAR      USD  \n2         True      REGULAR      USD  \n3         True      REGULAR      USD  \n4         True      REGULAR      USD  \n..         ...          ...      ...  \n67       False      REGULAR      USD  \n68       False      REGULAR      USD  \n69       False      REGULAR      USD  \n70       False      REGULAR      USD  \n71       False      REGULAR      USD  \n\n[72 rows x 14 columns]'